import {
  designSystemIds,
  type DesignFamily,
  type DesignSystem,
  type DesignSystemId,
} from './types';

export const designSystems: Readonly<Record<DesignSystemId, DesignSystem>> = {
  neoclassical: {
    id: 'neoclassical',
    index: 1,
    name: 'Neoclassical',
    descriptionKey: 'neoclassical',
    family: 'classical',
    hero: 'axial',
    voice: 'institutional',
    cursor: 'minimal',
    capabilities: ['pointer-field'],
    scene: { mobile: 'reduced', cost: 'medium', interaction: ['pointer', 'scroll'] },
    swatches: ['#f6f3ec', '#1c1a17', '#9a7b4f'],
    specimen: 'Aa',
  },
  baroque: {
    id: 'baroque',
    index: 2,
    name: 'Baroque',
    descriptionKey: 'baroque',
    family: 'ornamental',
    hero: 'theatrical',
    voice: 'institutional',
    cursor: 'ornamental',
    capabilities: ['pointer-field', 'ornament'],
    scene: { mobile: 'reduced', cost: 'high', interaction: ['pointer'] },
    swatches: ['#0b0705', '#f3e3c3', '#c9a227'],
    specimen: 'Aa',
  },
  aurora: {
    id: 'aurora',
    index: 3,
    name: 'Aurora',
    descriptionKey: 'aurora',
    family: 'atmospheric',
    hero: 'atmospheric',
    voice: 'atmospheric',
    cursor: 'glow',
    capabilities: ['pointer-field'],
    scene: { mobile: 'full', cost: 'medium', interaction: ['pointer', 'scroll'] },
    swatches: ['#050914', '#e8f4ff', '#57f2d0'],
    specimen: 'Aa',
  },
  ethereal: {
    id: 'ethereal',
    index: 4,
    name: 'Ethereal',
    descriptionKey: 'ethereal',
    family: 'atmospheric',
    hero: 'atmospheric',
    voice: 'atmospheric',
    cursor: 'feather',
    capabilities: ['pointer-field'],
    scene: { mobile: 'full', cost: 'medium', interaction: ['pointer'] },
    swatches: ['#f7f5fb', '#2e2a3a', '#b9a7e0'],
    specimen: 'Aa',
  },
  filigree: {
    id: 'filigree',
    index: 5,
    name: 'Filigree',
    descriptionKey: 'filigree',
    family: 'ornamental',
    hero: 'axial',
    voice: 'institutional',
    cursor: 'minimal',
    capabilities: ['ornament'],
    scene: { mobile: 'reduced', cost: 'medium', interaction: ['pointer'] },
    swatches: ['#12131a', '#efe9dd', '#b9995f'],
    specimen: 'Aa',
  },
  acanthus: {
    id: 'acanthus',
    index: 6,
    name: 'Acanthus',
    descriptionKey: 'acanthus',
    family: 'ornamental',
    hero: 'axial',
    voice: 'institutional',
    cursor: 'minimal',
    capabilities: ['ornament', 'pointer-field'],
    scene: { mobile: 'reduced', cost: 'medium', interaction: ['pointer', 'scroll'] },
    swatches: ['#efeade', '#22261f', '#6f7d4f'],
    specimen: 'Aa',
  },
  anthropomorphic: {
    id: 'anthropomorphic',
    index: 7,
    name: 'Anthropomorphic',
    descriptionKey: 'anthropomorphic',
    family: 'expressive',
    hero: 'character',
    voice: 'playful',
    cursor: 'character',
    capabilities: ['characters', 'pointer-field'],
    scene: { mobile: 'full', cost: 'medium', interaction: ['pointer'] },
    swatches: ['#fff6ec', '#2b2118', '#ff7a4d'],
    specimen: 'Aa',
  },
  'pixel-art': {
    id: 'pixel-art',
    index: 8,
    name: 'Pixel Art',
    descriptionKey: 'pixel-art',
    family: 'retro',
    hero: 'terminal',
    voice: 'terminal',
    cursor: 'pixel',
    capabilities: [],
    scene: { mobile: 'full', cost: 'low', interaction: ['pointer'] },
    swatches: ['#0d1117', '#c7f5d9', '#39ff88'],
    specimen: 'A_',
  },
  'conceptual-sketch': {
    id: 'conceptual-sketch',
    index: 9,
    name: 'Conceptual Sketch',
    descriptionKey: 'conceptual-sketch',
    family: 'modernist',
    hero: 'notebook',
    voice: 'flow',
    cursor: 'pencil',
    capabilities: ['ornament', 'system-readout'],
    scene: { mobile: 'reduced', cost: 'low', interaction: ['pointer'] },
    swatches: ['#f4f1e8', '#232323', '#2f6fd0'],
    specimen: 'Aa',
  },
  'luxury-typography': {
    id: 'luxury-typography',
    index: 10,
    name: 'Luxury Typography',
    descriptionKey: 'luxury-typography',
    family: 'modernist',
    hero: 'editorial',
    voice: 'editorial',
    cursor: 'editorial',
    capabilities: ['pointer-field'],
    scene: { mobile: 'reduced', cost: 'medium', interaction: ['pointer'] },
    swatches: ['#ffffff', '#000000', '#8a8a8a'],
    specimen: 'Aa',
  },

  japandi: {
    id: 'japandi',
    index: 11,
    name: 'Japandi',
    descriptionKey: 'japandi',
    family: 'domestic',
    hero: 'axial',
    voice: 'atmospheric',
    cursor: 'minimal',
    capabilities: ['pointer-field'],
    scene: { mobile: 'reduced', cost: 'low', interaction: ['pointer'] },
    swatches: ['#f3efe7', '#2c2a26', '#a8836a'],
    specimen: 'Aa',
  },
  memphis: {
    id: 'memphis',
    index: 12,
    name: 'Memphis',
    descriptionKey: 'memphis',
    family: 'expressive',
    hero: 'poster',
    voice: 'playful',
    cursor: 'blade',
    capabilities: [],
    scene: { mobile: 'full', cost: 'medium', interaction: ['pointer'] },
    swatches: ['#fdf6e3', '#141414', '#ff3b7f'],
    specimen: 'Aa',
  },
  bohemian: {
    id: 'bohemian',
    index: 13,
    name: 'Bohemian',
    descriptionKey: 'bohemian',
    family: 'domestic',
    hero: 'collage',
    voice: 'atmospheric',
    cursor: 'feather',
    capabilities: [],
    scene: { mobile: 'reduced', cost: 'medium', interaction: ['pointer'] },
    swatches: ['#2a1f1a', '#f3e7d8', '#c98b52'],
    specimen: 'Aa',
  },
  'shabby-chic': {
    id: 'shabby-chic',
    index: 14,
    name: 'Shabby Chic',
    descriptionKey: 'shabby-chic',
    family: 'domestic',
    hero: 'collage',
    voice: 'editorial',
    cursor: 'feather',
    capabilities: [],
    scene: { mobile: 'reduced', cost: 'medium', interaction: ['pointer'] },
    swatches: ['#faf3f2', '#4a3f42', '#c9a0a6'],
    specimen: 'Aa',
  },
  cottagecore: {
    id: 'cottagecore',
    index: 15,
    name: 'Cottagecore',
    descriptionKey: 'cottagecore',
    family: 'domestic',
    hero: 'atmospheric',
    voice: 'atmospheric',
    cursor: 'feather',
    capabilities: [],
    scene: { mobile: 'reduced', cost: 'medium', interaction: ['pointer', 'scroll'] },
    swatches: ['#f6f2e4', '#33402c', '#8fa860'],
    specimen: 'Aa',
  },
  victorian: {
    id: 'victorian',
    index: 16,
    name: 'Victorian',
    descriptionKey: 'victorian',
    family: 'ornamental',
    hero: 'theatrical',
    voice: 'institutional',
    cursor: 'ornamental',
    capabilities: ['ornament'],
    scene: { mobile: 'disabled', cost: 'high', interaction: ['pointer'] },
    swatches: ['#120e0c', '#e8dcc4', '#8c6a3f'],
    specimen: 'Aa',
  },
  'art-deco': {
    id: 'art-deco',
    index: 17,
    name: 'Art Deco',
    descriptionKey: 'art-deco',
    family: 'classical',
    hero: 'axial',
    voice: 'institutional',
    cursor: 'blade',
    capabilities: ['ornament'],
    scene: { mobile: 'reduced', cost: 'medium', interaction: ['pointer'] },
    swatches: ['#0e1418', '#f0e3c8', '#d4af59'],
    specimen: 'Aa',
  },
  'art-nouveau': {
    id: 'art-nouveau',
    index: 18,
    name: 'Art Nouveau',
    descriptionKey: 'art-nouveau',
    family: 'ornamental',
    hero: 'axial',
    voice: 'atmospheric',
    cursor: 'bloom',
    capabilities: ['ornament', 'pointer-field'],
    scene: { mobile: 'reduced', cost: 'high', interaction: ['pointer'] },
    swatches: ['#f2ede0', '#1f2a22', '#a2794a'],
    specimen: 'Aa',
  },
  'mystical-western': {
    id: 'mystical-western',
    index: 19,
    name: 'Mystical Western',
    descriptionKey: 'mystical-western',
    family: 'atmospheric',
    hero: 'theatrical',
    voice: 'atmospheric',
    cursor: 'lantern',
    capabilities: [],
    scene: { mobile: 'reduced', cost: 'medium', interaction: ['pointer', 'scroll'] },
    swatches: ['#0d0a14', '#f0e6d2', '#c46a3d'],
    specimen: 'Aa',
  },
  kitsch: {
    id: 'kitsch',
    index: 20,
    name: 'Kitsch',
    descriptionKey: 'kitsch',
    family: 'expressive',
    hero: 'collage',
    voice: 'playful',
    cursor: 'bloom',
    capabilities: [],
    scene: { mobile: 'reduced', cost: 'high', interaction: ['pointer'] },
    swatches: ['#ffe9f4', '#20122b', '#ff2e88'],
    specimen: 'Aa',
  },
  y2k: {
    id: 'y2k',
    index: 21,
    name: 'Y2K',
    descriptionKey: 'y2k',
    family: 'retro',
    hero: 'poster',
    voice: 'terminal',
    cursor: 'chrome',
    capabilities: [],
    scene: { mobile: 'reduced', cost: 'high', interaction: ['pointer'] },
    swatches: ['#dbe9ff', '#0a1230', '#8ab6ff'],
    specimen: 'Aa',
  },
  bauhaus: {
    id: 'bauhaus',
    index: 22,
    name: 'Bauhaus',
    descriptionKey: 'bauhaus',
    family: 'modernist',
    hero: 'modular',
    voice: 'flow',
    cursor: 'crosshair',
    capabilities: [],
    scene: { mobile: 'full', cost: 'low', interaction: ['pointer'] },
    swatches: ['#f2efe9', '#151515', '#e2231a'],
    specimen: 'Aa',
  },
  brutalism: {
    id: 'brutalism',
    index: 23,
    name: 'Brutalism',
    descriptionKey: 'brutalism',
    family: 'modernist',
    hero: 'poster',
    voice: 'manifesto',
    cursor: 'crosshair',
    capabilities: [],
    scene: { mobile: 'reduced', cost: 'medium', interaction: ['pointer', 'scroll'] },
    swatches: ['#c9c6bf', '#141414', '#8a8578'],
    specimen: 'Aa',
  },
  cybercore: {
    id: 'cybercore',
    index: 24,
    name: 'Cybercore',
    descriptionKey: 'cybercore',
    family: 'digital',
    hero: 'terminal',
    voice: 'terminal',
    cursor: 'crosshair',
    capabilities: ['system-readout'],
    scene: { mobile: 'reduced', cost: 'medium', interaction: ['pointer'] },
    swatches: ['#04060a', '#c8f8ff', '#00e5ff'],
    specimen: '01',
  },
  synthwave: {
    id: 'synthwave',
    index: 25,
    name: 'Synthwave',
    descriptionKey: 'synthwave',
    family: 'retro',
    hero: 'atmospheric',
    voice: 'manifesto',
    cursor: 'glow',
    capabilities: [],
    scene: { mobile: 'reduced', cost: 'medium', interaction: ['pointer', 'scroll'] },
    swatches: ['#100425', '#ffe9fb', '#ff2d95'],
    specimen: 'Aa',
  },

  vaporwave: {
    id: 'vaporwave',
    index: 26,
    name: 'Vaporwave',
    descriptionKey: 'vaporwave',
    family: 'retro',
    hero: 'collage',
    voice: 'editorial',
    cursor: 'glow',
    capabilities: [],
    scene: { mobile: 'reduced', cost: 'medium', interaction: ['pointer'] },
    swatches: ['#1a0f2e', '#f6e8ff', '#00e0c6'],
    specimen: 'Aa',
  },
  'pop-art': {
    id: 'pop-art',
    index: 27,
    name: 'Pop Art',
    descriptionKey: 'pop-art',
    family: 'expressive',
    hero: 'poster',
    voice: 'manifesto',
    cursor: 'blade',
    capabilities: [],
    scene: { mobile: 'full', cost: 'medium', interaction: ['pointer'] },
    swatches: ['#fff8e1', '#101010', '#e8112d'],
    specimen: 'Aa',
  },
  'bento-box': {
    id: 'bento-box',
    index: 28,
    name: 'Bento Box',
    descriptionKey: 'bento-box',
    family: 'digital',
    hero: 'modular',
    voice: 'spec',
    cursor: 'minimal',
    capabilities: ['system-readout'],
    scene: { mobile: 'full', cost: 'medium', interaction: ['pointer'] },
    swatches: ['#0e0f12', '#f2f4f8', '#7c9cff'],
    specimen: 'Aa',
  },
  graffiti: {
    id: 'graffiti',
    index: 29,
    name: 'Graffiti',
    descriptionKey: 'graffiti',
    family: 'expressive',
    hero: 'poster',
    voice: 'manifesto',
    cursor: 'spray',
    capabilities: [],
    scene: { mobile: 'reduced', cost: 'medium', interaction: ['pointer', 'scroll'] },
    swatches: ['#1a1a1a', '#f4f4f0', '#39ff6a'],
    specimen: 'Aa',
  },
  tenebrism: {
    id: 'tenebrism',
    index: 30,
    name: 'Tenebrism',
    descriptionKey: 'tenebrism',
    family: 'classical',
    hero: 'theatrical',
    voice: 'atmospheric',
    cursor: 'lantern',
    capabilities: ['pointer-field'],
    scene: { mobile: 'reduced', cost: 'medium', interaction: ['pointer'] },
    swatches: ['#050505', '#e8ded0', '#c98a2e'],
    specimen: 'Aa',
  },
  gothic: {
    id: 'gothic',
    index: 31,
    name: 'Gothic',
    descriptionKey: 'gothic',
    family: 'ornamental',
    hero: 'theatrical',
    voice: 'institutional',
    cursor: 'lantern',
    capabilities: ['ornament'],
    scene: { mobile: 'disabled', cost: 'high', interaction: ['pointer', 'scroll'] },
    swatches: ['#0a0a10', '#ded6e6', '#7a4fa8'],
    specimen: 'Aa',
  },
  pointillism: {
    id: 'pointillism',
    index: 32,
    name: 'Pointillism',
    descriptionKey: 'pointillism',
    family: 'atmospheric',
    hero: 'atmospheric',
    voice: 'atmospheric',
    cursor: 'bloom',
    capabilities: ['pointer-field'],
    scene: { mobile: 'reduced', cost: 'high', interaction: ['pointer'] },
    swatches: ['#f4f1ea', '#20242c', '#e06c3a'],
    specimen: 'Aa',
  },
  'mixed-media': {
    id: 'mixed-media',
    index: 33,
    name: 'Mixed Media',
    descriptionKey: 'mixed-media',
    family: 'expressive',
    hero: 'collage',
    voice: 'atmospheric',
    cursor: 'stitch',
    capabilities: [],
    scene: { mobile: 'reduced', cost: 'medium', interaction: ['pointer'] },
    swatches: ['#e9e4d8', '#1c1a17', '#b8452f'],
    specimen: 'Aa',
  },
  steampunk: {
    id: 'steampunk',
    index: 34,
    name: 'Steampunk',
    descriptionKey: 'steampunk',
    family: 'retro',
    hero: 'theatrical',
    voice: 'spec',
    cursor: 'brass',
    capabilities: ['ornament'],
    scene: { mobile: 'disabled', cost: 'high', interaction: ['pointer'] },
    swatches: ['#17110a', '#e8d5ae', '#b07d3a'],
    specimen: 'Aa',
  },
  kawaii: {
    id: 'kawaii',
    index: 35,
    name: 'Kawaii',
    descriptionKey: 'kawaii',
    family: 'expressive',
    hero: 'character',
    voice: 'playful',
    cursor: 'character',
    capabilities: ['characters'],
    scene: { mobile: 'full', cost: 'medium', interaction: ['pointer'] },
    swatches: ['#fff0f6', '#3d2b3a', '#ff8fc4'],
    specimen: 'Aa',
  },
  coquette: {
    id: 'coquette',
    index: 36,
    name: 'Coquette',
    descriptionKey: 'coquette',
    family: 'ornamental',
    hero: 'editorial',
    voice: 'editorial',
    cursor: 'feather',
    capabilities: ['ornament'],
    scene: { mobile: 'reduced', cost: 'medium', interaction: ['pointer'] },
    swatches: ['#fdf3f5', '#3a2c30', '#d9899b'],
    specimen: 'Aa',
  },
  surrealism: {
    id: 'surrealism',
    index: 37,
    name: 'Surrealism',
    descriptionKey: 'surrealism',
    family: 'expressive',
    hero: 'theatrical',
    voice: 'atmospheric',
    cursor: 'bloom',
    capabilities: [],
    scene: { mobile: 'reduced', cost: 'high', interaction: ['pointer', 'scroll'] },
    swatches: ['#e8dfd0', '#141824', '#3f6ee0'],
    specimen: 'Aa',
  },
  utilitarian: {
    id: 'utilitarian',
    index: 38,
    name: 'Utilitarian',
    descriptionKey: 'utilitarian',
    family: 'modernist',
    hero: 'terminal',
    voice: 'spec',
    cursor: 'crosshair',
    capabilities: ['system-readout'],
    scene: { mobile: 'full', cost: 'low', interaction: ['pointer'] },
    swatches: ['#16181a', '#e6e8ea', '#ff8a1f'],
    specimen: 'Aa',
  },
  'mid-century': {
    id: 'mid-century',
    index: 39,
    name: 'Mid-Century',
    descriptionKey: 'mid-century',
    family: 'modernist',
    hero: 'axial',
    voice: 'editorial',
    cursor: 'minimal',
    capabilities: [],
    scene: { mobile: 'reduced', cost: 'medium', interaction: ['pointer'] },
    swatches: ['#f3ead9', '#26221d', '#d2762f'],
    specimen: 'Aa',
  },
  scrapbook: {
    id: 'scrapbook',
    index: 40,
    name: 'Scrapbook',
    descriptionKey: 'scrapbook',
    family: 'domestic',
    hero: 'collage',
    voice: 'playful',
    cursor: 'stitch',
    capabilities: [],
    scene: { mobile: 'reduced', cost: 'medium', interaction: ['pointer'] },
    swatches: ['#f2ece1', '#2a2620', '#4d7ea8'],
    specimen: 'Aa',
  },

  'frutiger-aero': {
    id: 'frutiger-aero',
    index: 41,
    name: 'Frutiger Aero',
    descriptionKey: 'frutiger-aero',
    family: 'digital',
    hero: 'atmospheric',
    voice: 'playful',
    cursor: 'bloom',
    capabilities: [],
    scene: { mobile: 'reduced', cost: 'high', interaction: ['pointer'] },
    swatches: ['#e6f6ff', '#0b2b3c', '#4fd8ff'],
    specimen: 'Aa',
  },
  'dark-academia': {
    id: 'dark-academia',
    index: 42,
    name: 'Dark Academia',
    descriptionKey: 'dark-academia',
    family: 'classical',
    hero: 'theatrical',
    voice: 'institutional',
    cursor: 'lantern',
    capabilities: ['ornament'],
    scene: { mobile: 'disabled', cost: 'high', interaction: ['pointer'] },
    swatches: ['#131009', '#e6dcc3', '#a4762f'],
    specimen: 'Aa',
  },
  'light-academia': {
    id: 'light-academia',
    index: 43,
    name: 'Light Academia',
    descriptionKey: 'light-academia',
    family: 'classical',
    hero: 'editorial',
    voice: 'institutional',
    cursor: 'minimal',
    capabilities: [],
    scene: { mobile: 'reduced', cost: 'medium', interaction: ['pointer'] },
    swatches: ['#f7f2e6', '#2e2a22', '#8f7440'],
    specimen: 'Aa',
  },
  'wabi-sabi': {
    id: 'wabi-sabi',
    index: 44,
    name: 'Wabi Sabi',
    descriptionKey: 'wabi-sabi',
    family: 'domestic',
    hero: 'axial',
    voice: 'atmospheric',
    cursor: 'minimal',
    capabilities: ['pointer-field'],
    scene: { mobile: 'reduced', cost: 'medium', interaction: ['pointer'] },
    swatches: ['#eae5da', '#33302a', '#8c7a63'],
    specimen: 'Aa',
  },
  'wild-west': {
    id: 'wild-west',
    index: 45,
    name: 'Wild West',
    descriptionKey: 'wild-west',
    family: 'retro',
    hero: 'theatrical',
    voice: 'manifesto',
    cursor: 'lantern',
    capabilities: [],
    scene: { mobile: 'reduced', cost: 'medium', interaction: ['pointer', 'scroll'] },
    swatches: ['#e8d9b8', '#2b1d12', '#b5471f'],
    specimen: 'Aa',
  },
  nautical: {
    id: 'nautical',
    index: 46,
    name: 'Nautical',
    descriptionKey: 'nautical',
    family: 'domestic',
    hero: 'atmospheric',
    voice: 'atmospheric',
    cursor: 'minimal',
    capabilities: ['pointer-field'],
    scene: { mobile: 'reduced', cost: 'medium', interaction: ['pointer', 'scroll'] },
    swatches: ['#0b1f2e', '#eef4f7', '#2f8fbf'],
    specimen: 'Aa',
  },
  rebus: {
    id: 'rebus',
    index: 47,
    name: 'Rebus',
    descriptionKey: 'rebus',
    family: 'expressive',
    hero: 'modular',
    voice: 'flow',
    cursor: 'crosshair',
    capabilities: [],
    scene: { mobile: 'full', cost: 'medium', interaction: ['pointer'] },
    swatches: ['#f0ede4', '#1a1a1a', '#e0483c'],
    specimen: 'Aa',
  },
  glassmorphism: {
    id: 'glassmorphism',
    index: 48,
    name: 'Glassmorphism',
    descriptionKey: 'glassmorphism',
    family: 'digital',
    hero: 'atmospheric',
    voice: 'editorial',
    cursor: 'bloom',
    capabilities: ['pointer-field'],
    scene: { mobile: 'reduced', cost: 'high', interaction: ['pointer'] },
    swatches: ['#0f1424', '#f0f4ff', '#8ab4ff'],
    specimen: 'Aa',
  },
  'modular-typography': {
    id: 'modular-typography',
    index: 49,
    name: 'Modular Typography',
    descriptionKey: 'modular-typography',
    family: 'modernist',
    hero: 'modular',
    voice: 'flow',
    cursor: 'editorial',
    capabilities: [],
    scene: { mobile: 'full', cost: 'medium', interaction: ['pointer'] },
    swatches: ['#111111', '#f5f5f0', '#ff4d1f'],
    specimen: 'Aa',
  },
  'neo-brutalism': {
    id: 'neo-brutalism',
    index: 50,
    name: 'Neo-Brutalism',
    descriptionKey: 'neo-brutalism',
    family: 'digital',
    hero: 'poster',
    voice: 'manifesto',
    cursor: 'crosshair',
    capabilities: [],
    scene: { mobile: 'full', cost: 'low', interaction: ['pointer'] },
    swatches: ['#fdf05c', '#101010', '#2d5bff'],
    specimen: 'Aa',
  },
};

export const designSystemList: readonly DesignSystem[] = designSystemIds.map(
  (id) => designSystems[id],
);

export const designFamilies: readonly DesignFamily[] = [
  'classical',
  'ornamental',
  'atmospheric',
  'modernist',
  'retro',
  'digital',
  'expressive',
  'domestic',
];

export const designSystemsByFamily: Readonly<
  Record<DesignFamily, readonly DesignSystem[]>
> = designFamilies.reduce(
  (grouped, family) => {
    grouped[family] = designSystemList.filter((system) => system.family === family);
    return grouped;
  },
  {} as Record<DesignFamily, readonly DesignSystem[]>,
);

export function getDesignSystem(id: DesignSystemId): DesignSystem {
  return designSystems[id];
}

export function hasCapability(
  id: DesignSystemId,
  capability: DesignSystem['capabilities'][number],
): boolean {
  return designSystems[id].capabilities.includes(capability);
}
